In [1]:
import pandas as pd
import numpy as np
import sklearn.model_selection as ms
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report
import warnings
warnings.filterwarnings("ignore")
from tensorflow import keras
from sklearn.preprocessing import scale

In [2]:
features = pd.read_csv("/content/drive/MyDrive/NYC DSA Capstone Project/Data/featuresCD.csv", low_memory = False)
features.drop(["Unnamed: 0"], axis = 1, inplace = True)
features

loan_status_trim  state_income  ...  mths_since_last_major_derog  grade
0                      0             2  ...                         30.0      4
1                      0             1  ...                          0.0      4
2                      0             2  ...                          0.0      4
3                      0             2  ...                          0.0      4
4                      0             2  ...                          0.0      4
...                  ...           ...  ...                          ...    ...
583975                 0             2  ...                          0.0      4
583976                 0             3  ...                          0.0      4
583977                 1             2  ...                          0.0      4
583978                 0             2  ...                         68.0      4
583979                 1             2  ...                         67.0      4

[583980 rows x 28 columns]

In [3]:
data = features.iloc[:,1:]
targets = features.iloc[:,0]

In [4]:
data

state_income  annual_inc_joint  ...  mths_since_last_major_derog  grade
0                  2           55000.0  ...                         30.0      4
1                  1           65000.0  ...                          0.0      4
2                  2           34000.0  ...                          0.0      4
3                  2           64000.0  ...                          0.0      4
4                  2          112000.0  ...                          0.0      4
...              ...               ...  ...                          ...    ...
583975             2          119000.0  ...                          0.0      4
583976             3          180792.0  ...                          0.0      4
583977             2          157000.0  ...                          0.0      4
583978             2          150000.0  ...                         68.0      4
583979             2          110000.0  ...                         67.0      4

[583980 rows x 27 columns]

In [5]:
data = np.array(data)
data

array([[2.00e+00, 5.50e+04, 1.00e+00, ..., 3.00e+01, 3.00e+01, 4.00e+00],
       [1.00e+00, 6.50e+04, 1.00e+00, ..., 6.00e+00, 0.00e+00, 4.00e+00],
       [2.00e+00, 3.40e+04, 1.00e+00, ..., 0.00e+00, 0.00e+00, 4.00e+00],
       ...,
       [2.00e+00, 1.57e+05, 1.00e+00, ..., 0.00e+00, 0.00e+00, 4.00e+00],
       [2.00e+00, 1.50e+05, 1.00e+00, ..., 6.80e+01, 6.80e+01, 4.00e+00],
       [2.00e+00, 1.10e+05, 1.00e+00, ..., 6.70e+01, 6.70e+01, 4.00e+00]])

In [6]:
targets = np.array(targets)
targets

array([0, 0, 0, ..., 1, 0, 1])

In [7]:
train_features,  val_features, train_targets, val_targets = train_test_split(data, targets, test_size = 0.3, stratify = targets, shuffle = True)
print("Number of training feature samples:", len(train_features))
print("Number of validation feature samples:", len(val_features))
print("Number of training targets:", len(train_targets))
print("Number of validation targets:", len(val_targets))

Number of training feature samples: 408786
Number of validation feature samples: 175194
Number of training targets: 408786
Number of validation targets: 175194


In [8]:
train_features

array([[2.00e+00, 1.35e+05, 1.00e+00, ..., 4.50e+01, 4.50e+01, 4.00e+00],
       [2.00e+00, 4.20e+04, 1.00e+00, ..., 0.00e+00, 0.00e+00, 4.00e+00],
       [2.00e+00, 7.70e+04, 0.00e+00, ..., 5.00e+00, 5.00e+00, 4.00e+00],
       ...,
       [3.00e+00, 6.60e+04, 1.00e+00, ..., 4.40e+01, 0.00e+00, 3.00e+00],
       [3.00e+00, 7.50e+04, 1.00e+00, ..., 0.00e+00, 0.00e+00, 3.00e+00],
       [1.00e+00, 1.50e+05, 1.00e+00, ..., 0.00e+00, 0.00e+00, 4.00e+00]])

In [9]:
train_targets

array([0, 1, 1, ..., 0, 0, 0])

In [10]:
val_features

array([[3.00e+00, 4.40e+04, 1.00e+00, ..., 0.00e+00, 0.00e+00, 4.00e+00],
       [3.00e+00, 6.22e+04, 1.00e+00, ..., 0.00e+00, 0.00e+00, 4.00e+00],
       [3.00e+00, 5.20e+04, 1.00e+00, ..., 0.00e+00, 0.00e+00, 4.00e+00],
       ...,
       [3.00e+00, 4.50e+04, 1.00e+00, ..., 0.00e+00, 0.00e+00, 3.00e+00],
       [2.00e+00, 6.53e+04, 1.00e+00, ..., 6.40e+01, 6.40e+01, 4.00e+00],
       [2.00e+00, 5.80e+04, 1.00e+00, ..., 7.40e+01, 0.00e+00, 4.00e+00]])

In [11]:
val_targets

array([0, 0, 0, ..., 0, 0, 1])

In [12]:
# train_features = train_features.reshape(-1,1)
# val_features   = val_features.reshape(-1,1)
# train_targets = train_features.reshape(-1,1)
# val_targets   = val_features.reshape(-1,1)

In [13]:
# num_val_samples = int(len(features) * 0.2)
# train_features = features[:-num_val_samples]
# train_targets = targets[:-num_val_samples]
# val_features = features[-num_val_samples:]
# val_targets = targets[-num_val_samples:]

# print("Number of training samples:", len(train_features))
# print("Number of validation samples:", len(val_features))

In [14]:
train_features = scale(train_features)
val_features   = scale(val_features)

In [15]:
train_targets

array([0, 1, 1, ..., 0, 0, 0])

In [16]:
model = keras.Sequential(
    [
        keras.layers.Dense(
            150, activation="relu", input_shape=(train_features.shape[-1],)
        ),
        keras.layers.Dense(150, activation = "relu"),
        #keras.layers.Dropout(0.3),
       keras.layers.Dense(150, activation="relu"),
        # keras.layers.Dropout(0.3),
        keras.layers.Dense(150, activation="relu"),\
        #keras.layers.Dense(20, activation="relu"),
        keras.layers.Dense(1, activation="sigmoid"),
    ]
)
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 150)               4200      
_________________________________________________________________
dense_1 (Dense)              (None, 150)               22650     
_________________________________________________________________
dense_2 (Dense)              (None, 150)               22650     
_________________________________________________________________
dense_3 (Dense)              (None, 150)               22650     
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 151       
Total params: 72,301
Trainable params: 72,301
Non-trainable params: 0
_________________________________________________________________


In [27]:
%%time

metrics = [
   keras.metrics.BinaryAccuracy(
    name="binary_accuracy", dtype=None, threshold = 0.97
)
]

lr_schedule = keras.optimizers.schedules.ExponentialDecay(
    initial_learning_rate=0.01,
    decay_steps=20,
    decay_rate=0.9)

model.compile(
    optimizer=keras.optimizers.SGD(lr_schedule), loss="binary_crossentropy", metrics = metrics
)

callbacks = [keras.callbacks.ModelCheckpoint("Default_loans_model_at_epoch_{epoch}.h5")]


model.fit(
    train_features,
    train_targets,
    batch_size = 10,
    epochs = 3,
    verbose = 2,
    callbacks=callbacks,
    validation_data=(val_features, val_targets),
    validation_split = 0.2,
    validation_freq = 1,
    shuffle = True,
    class_weight = {0:0.65, 1:2},

)

Epoch 1/3
32703/32703 - 44s - loss: 0.6809 - binary_accuracy: 0.7477 - val_loss: 0.7002 - val_binary_accuracy: 0.7498
Epoch 2/3
32703/32703 - 46s - loss: 0.6809 - binary_accuracy: 0.7477 - val_loss: 0.7002 - val_binary_accuracy: 0.7498
Epoch 3/3
32703/32703 - 45s - loss: 0.6809 - binary_accuracy: 0.7477 - val_loss: 0.7002 - val_binary_accuracy: 0.7498
CPU times: user 3min 12s, sys: 12.1 s, total: 3min 25s
Wall time: 2min 14s


In [28]:
#dir(model)

In [29]:
%%time
predictions_train = model.predict_classes(train_features)
print(predictions_train)

[[0]
 [0]
 [0]
 ...
 [1]
 [1]
 [0]]
CPU times: user 11.2 s, sys: 1.08 s, total: 12.3 s
Wall time: 9.4 s


In [30]:
%%time
predictions_test = model.predict_classes(val_features)
print(predictions_test)

[[1]
 [0]
 [0]
 ...
 [1]
 [0]
 [0]]
CPU times: user 4.79 s, sys: 451 ms, total: 5.24 s
Wall time: 4.02 s


In [32]:
%%time
print("-"*100)
print("Training")
print(confusion_matrix(y_true = train_targets, y_pred = predictions_train))
print("-"*100)
print("Validation")
print(confusion_matrix(y_true = val_targets, y_pred = predictions_test))
print("-"*100)

----------------------------------------------------------------------------------------------------
Training
[[143660 162178]
 [ 38129  64819]]
----------------------------------------------------------------------------------------------------
Validation
[[61209 69864]
 [16449 27672]]
----------------------------------------------------------------------------------------------------
CPU times: user 570 ms, sys: 4.4 ms, total: 574 ms
Wall time: 574 ms
