In [1]:
import pandas as pd
import numpy as np
import sklearn.model_selection as ms
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report
import warnings
warnings.filterwarnings("ignore")
from tensorflow import keras
from sklearn.preprocessing import scale

In [4]:
# features = pd.read_csv("/content/drive/MyDrive/NYC DSA Capstone Project/Data/featuresCD.csv", low_memory = False)
# features.drop(["Unnamed: 0"], axis = 1, inplace = True)
features = pd.read_csv("/content/drive/MyDrive/NYC DSA Capstone Project/Data/features.csv", low_memory = False)
features.drop(["Unnamed: 0"], axis = 1, inplace = True)
features

loan_status_trim  state_income  ...  mths_since_last_major_derog  grade
0                       0             2  ...                         30.0      4
1                       0             1  ...                          0.0      4
2                       0             0  ...                          0.0      5
3                       0             2  ...                          0.0      1
4                       0             2  ...                          0.0      4
...                   ...           ...  ...                          ...    ...
1348094                 0             3  ...                          0.0      5
1348095                 0             3  ...                          0.0      4
1348096                 1             2  ...                          0.0      4
1348097                 0             2  ...                         68.0      4
1348098                 1             2  ...                         67.0      4

[1348099 rows x 28 columns]

In [5]:
data = features.iloc[:,1:]
targets = features.iloc[:,0]

In [6]:
data

state_income  annual_inc_joint  ...  mths_since_last_major_derog  grade
0                   2           55000.0  ...                         30.0      4
1                   1           65000.0  ...                          0.0      4
2                   0           71000.0  ...                          0.0      5
3                   2          104433.0  ...                          0.0      1
4                   2           34000.0  ...                          0.0      4
...               ...               ...  ...                          ...    ...
1348094             3          130000.0  ...                          0.0      5
1348095             3          180792.0  ...                          0.0      4
1348096             2          157000.0  ...                          0.0      4
1348097             2          150000.0  ...                         68.0      4
1348098             2          110000.0  ...                         67.0      4

[1348099 rows x 27 columns]

In [7]:
data = np.array(data)
data

array([[2.00e+00, 5.50e+04, 1.00e+00, ..., 3.00e+01, 3.00e+01, 4.00e+00],
       [1.00e+00, 6.50e+04, 1.00e+00, ..., 6.00e+00, 0.00e+00, 4.00e+00],
       [0.00e+00, 7.10e+04, 0.00e+00, ..., 0.00e+00, 0.00e+00, 5.00e+00],
       ...,
       [2.00e+00, 1.57e+05, 1.00e+00, ..., 0.00e+00, 0.00e+00, 4.00e+00],
       [2.00e+00, 1.50e+05, 1.00e+00, ..., 6.80e+01, 6.80e+01, 4.00e+00],
       [2.00e+00, 1.10e+05, 1.00e+00, ..., 6.70e+01, 6.70e+01, 4.00e+00]])

In [8]:
targets = np.array(targets)
targets

array([0, 0, 0, ..., 1, 0, 1])

In [9]:
train_features,  val_features, train_targets, val_targets = train_test_split(data, targets, test_size = 0.3, stratify = targets, shuffle = True)
print("Number of training feature samples:", len(train_features))
print("Number of validation feature samples:", len(val_features))
print("Number of training targets:", len(train_targets))
print("Number of validation targets:", len(val_targets))

Number of training feature samples: 943669
Number of validation feature samples: 404430
Number of training targets: 943669
Number of validation targets: 404430


In [10]:
train_features

array([[2.0e+00, 4.0e+04, 1.0e+00, ..., 3.4e+01, 3.4e+01, 2.0e+00],
       [0.0e+00, 8.3e+04, 1.0e+00, ..., 0.0e+00, 0.0e+00, 5.0e+00],
       [2.0e+00, 6.5e+04, 1.0e+00, ..., 4.0e+00, 4.0e+00, 4.0e+00],
       ...,
       [2.0e+00, 5.9e+04, 1.0e+00, ..., 4.2e+01, 0.0e+00, 3.0e+00],
       [3.0e+00, 8.5e+04, 1.0e+00, ..., 0.0e+00, 0.0e+00, 3.0e+00],
       [2.0e+00, 2.5e+04, 1.0e+00, ..., 0.0e+00, 0.0e+00, 3.0e+00]])

In [11]:
train_targets

array([0, 0, 0, ..., 0, 1, 0])

In [12]:
val_features

array([[2.00e+00, 6.10e+04, 1.00e+00, ..., 1.50e+01, 0.00e+00, 6.00e+00],
       [2.00e+00, 5.00e+04, 1.00e+00, ..., 0.00e+00, 0.00e+00, 4.00e+00],
       [0.00e+00, 7.00e+04, 1.00e+00, ..., 0.00e+00, 0.00e+00, 5.00e+00],
       ...,
       [2.00e+00, 8.10e+04, 1.00e+00, ..., 0.00e+00, 0.00e+00, 5.00e+00],
       [2.00e+00, 4.57e+04, 1.00e+00, ..., 4.70e+01, 4.70e+01, 5.00e+00],
       [2.00e+00, 6.50e+04, 1.00e+00, ..., 0.00e+00, 0.00e+00, 5.00e+00]])

In [13]:
val_targets

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
# train_features = train_features.reshape(-1,1)
# val_features   = val_features.reshape(-1,1)
# train_targets = train_features.reshape(-1,1)
# val_targets   = val_features.reshape(-1,1)

In [ ]:
# num_val_samples = int(len(features) * 0.2)
# train_features = features[:-num_val_samples]
# train_targets = targets[:-num_val_samples]
# val_features = features[-num_val_samples:]
# val_targets = targets[-num_val_samples:]

# print("Number of training samples:", len(train_features))
# print("Number of validation samples:", len(val_features))

In [14]:
train_features = scale(train_features)
val_features   = scale(val_features)

In [15]:
train_targets

array([0, 0, 0, ..., 0, 1, 0])

In [16]:
model = keras.Sequential(
    [
        keras.layers.Dense(
            150, activation="relu", input_shape=(train_features.shape[-1],)
        ),
        keras.layers.Dense(150, activation = "relu"),
        #keras.layers.Dropout(0.3),
        keras.layers.Dense(150, activation="relu"),
        # keras.layers.Dropout(0.3),
        keras.layers.Dense(150, activation="relu"),\
        #keras.layers.Dense(20, activation="relu"),
        keras.layers.Dense(1, activation="sigmoid"),
    ]
)
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 150)               4200      
_________________________________________________________________
dense_1 (Dense)              (None, 150)               22650     
_________________________________________________________________
dense_2 (Dense)              (None, 150)               22650     
_________________________________________________________________
dense_3 (Dense)              (None, 150)               22650     
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 151       
Total params: 72,301
Trainable params: 72,301
Non-trainable params: 0
_________________________________________________________________


In [26]:
%%time

metrics = [
   keras.metrics.BinaryAccuracy(
    name="binary_accuracy", dtype=None, threshold = 0.97
)
]

lr_schedule = keras.optimizers.schedules.ExponentialDecay(
    initial_learning_rate=0.01,
    decay_steps=20,
    decay_rate=0.9)

model.compile(
    optimizer=keras.optimizers.SGD(lr_schedule), loss="binary_crossentropy", metrics = metrics
)

callbacks = [keras.callbacks.ModelCheckpoint("Default_loans_model_at_epoch_{epoch}.h5")]


model.fit(
    train_features,
    train_targets,
    batch_size = 10,
    epochs = 3,
    verbose = 2,
    callbacks=callbacks,
    validation_data=(val_features, val_targets),
    validation_split = 0.2,
    validation_freq = 1,
    shuffle = True,
    class_weight = {0:0.5, 1:2},

)

Epoch 1/3
75494/75494 - 165s - loss: 0.5270 - binary_accuracy: 0.7997 - val_loss: 0.6761 - val_binary_accuracy: 0.8021
Epoch 2/3
75494/75494 - 166s - loss: 0.5270 - binary_accuracy: 0.7997 - val_loss: 0.6761 - val_binary_accuracy: 0.8021
Epoch 3/3
75494/75494 - 165s - loss: 0.5270 - binary_accuracy: 0.7997 - val_loss: 0.6761 - val_binary_accuracy: 0.8021
CPU times: user 13min 25s, sys: 2min 14s, total: 15min 39s
Wall time: 8min 16s


In [27]:
#dir(model)

In [28]:
%%time
predictions_train = model.predict_classes(train_features)
print(predictions_train)

[[1]
 [0]
 [0]
 ...
 [1]
 [1]
 [1]]
CPU times: user 32.5 s, sys: 5.23 s, total: 37.7 s
Wall time: 22.5 s


In [29]:
%%time
predictions_test = model.predict_classes(val_features)
print(predictions_test)

[[0]
 [1]
 [0]
 ...
 [1]
 [0]
 [0]]
CPU times: user 12.7 s, sys: 1.96 s, total: 14.6 s
Wall time: 8.69 s


In [30]:
%%time
print("-"*100)
print("Training")
print(confusion_matrix(y_true = train_targets, y_pred = predictions_train))
print("-"*100)
print("Validation")
print(confusion_matrix(y_true = val_targets, y_pred = predictions_test))
print("-"*100)

----------------------------------------------------------------------------------------------------
Training
[[425779 329338]
 [ 58491 130061]]
----------------------------------------------------------------------------------------------------
Validation
[[182675 140947]
 [ 25000  55808]]
----------------------------------------------------------------------------------------------------
CPU times: user 1.23 s, sys: 0 ns, total: 1.23 s
Wall time: 1.23 s
